// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { SupabaseClient, Session, User } from "@supabase/supabase-js";
import type { Database } from "./types";
import { DEMO_ACCOUNT_EMAIL } from "@/lib/demoData";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

const createDemoSession = (): Session => {
  const now = new Date();
  const baseTimestamp = Math.floor(now.getTime() / 1000);

  const demoUser: User = {
    id: "demo-user-id",
    email: DEMO_ACCOUNT_EMAIL,
    aud: "authenticated",
    app_metadata: { provider: "email" },
    user_metadata: { full_name: "Demo Learner", role: "student" },
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
    last_sign_in_at: now.toISOString(),
    role: "authenticated",
    confirmed_at: now.toISOString(),
    email_confirmed_at: now.toISOString(),
    identities: [],
    factors: [],
    phone: "",
    phone_confirmed_at: null,
    recovery_sent_at: null,
    invited_at: null,
    action_link: null,
    email_change_sent_at: null,
    new_email: null,
    new_phone: null,
    confirmation_sent_at: null,
    is_anonymous: false,
  };

  return {
    access_token: "demo-access-token",
    refresh_token: "demo-refresh-token",
    token_type: "bearer",
    expires_in: 3600,
    expires_at: baseTimestamp + 3600,
    user: demoUser,
    provider_refresh_token: null,
    provider_token: null,
  };
};

const createDemoQueryResponse = () => ({
  data: null,
  error: new Error("Supabase is not configured. Showing demo content only."),
});

const createDemoQueryBuilder = () => {
  const responsePromise = Promise.resolve(createDemoQueryResponse());

  const builder: any = {
    select: () => builder,
    eq: () => builder,
    order: () => responsePromise,
    single: () => responsePromise,
    maybeSingle: () => responsePromise,
    insert: () => responsePromise,
    update: () => ({
      eq: () => responsePromise,
    }),
  };

  return builder;
};

const createDemoSupabaseClient = (): SupabaseClient<Database> => {
  const session = createDemoSession();

  const demoAuth = {
    getSession: () => Promise.resolve({ data: { session }, error: null }),
    onAuthStateChange: (callback: (event: string, session: Session | null) => void) => {
      callback("SIGNED_IN", session);
      return {
        data: { subscription: { unsubscribe: () => undefined } },
        error: null,
      };
    },
    signUp: async () => ({ data: { user: session.user, session }, error: null }),
    signInWithPassword: async () => ({ data: { user: session.user, session }, error: null }),
    signOut: async () => ({ error: null }),
  };

  const demoFrom = () => {
    const builder = createDemoQueryBuilder();
    return builder;
  };

  return {
    auth: demoAuth,
    from: demoFrom,
  } as unknown as SupabaseClient<Database>;
};

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createDemoSupabaseClient();

export const isUsingDemoSupabase = !isSupabaseConfigured;
